export const route={
    LOGIN:`/api/auth/login`,
    POSTS:  `/api/posts`,
    POSTID:`/api/posts/`,
    USERPOSTS:`/api/posts/user/`,
    CREATEPOST:`/api/posts`,
    DELETEPOST:`/api/posts/`,
    EDITPOST:`/api/posts/edit/`,
    LIKEPOST:`/api/posts/like/`,
    DISLIKEPOST:`/api/posts/dislike/`,
    ALLUSERS:`/api/users`,
    GETUSERASID:`/api/users/id/`,
    GETUSERASNAME:`/api/users/name/`,
    EDITUSER:`/api/users/edit`,
    ALLBOOKMARKPOST:`/api/users/bookmark`,
    BOOKMARKPOST:`/api/users/bookmark/`,
    UNBOOKMARKPOST:`/api/users/remove-bookmark/`,
    FOLLOWUSER:`/api/users/follow/`,
    UNFOLOWUSER:`/api/users/unfollow/`,
}